name: ErfanGSIs-build-AB

on: 
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
      ROM_TYPE:
        description: 'ROM_TYPE'
        required: true
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: | 
            git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh
              
       - name: Install Python
         run: |
           wget https://www.python.org/ftp/python/3.10.6/Python-3.10.6.tgz
           tar -zxvf Python-3.10.6.tgz
           cd Python-3.10.6
           ./configure
           make
           sudo make install
           sudo apt remove python-2.7.17
    
       - name: Setting up requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --ab "${{ github.event.inputs.ROM_URL }}" "${{ github.event.inputs.ROM_TYPE }}"
              
       #- name: Pack GSI
         #run: |

           #sudo apt install p7zip-full
           #7za a -t7z -r Generic ErfanGSIs/output/*
              
       - name: Upload GSI
         uses: actions/upload-artifact@v3
         with:
           name: my-artifact
           path: ErfanGSIs/output/*


